### ISSUE TITLE
Error on deploying 2.7

### ISSUE THREAD

**Issue by mohlek** [katharsis-project/katharsis-framework#176]
Im having touble deploying katharsis 2.7 on my wildfly 10.1.

I upgraded from 2.6 to 2.7 and now my server wont start.

```
12:07:37,328 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 17) MSC000001: Failed to start service jboss.undertow.deployment.default-server.default-host./DDGRestAPI: org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./DDGRestAPI: java.lang.NoSuchMethodError: io.katharsis.dispatcher.RequestDispatcher.<init>(Lio/katharsis/module/ModuleRegistry;Lio/katharsis/dispatcher/registry/ControllerRegistry;Lio/katharsis/errorhandling/mapper/ExceptionMapperRegistry;Lio/katharsis/queryspec/internal/QueryAdapterBuilder;)V
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:85)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jboss.threads.JBossThread.run(JBossThread.java:320)
Caused by: java.lang.NoSuchMethodError: io.katharsis.dispatcher.RequestDispatcher.<init>(Lio/katharsis/module/ModuleRegistry;Lio/katharsis/dispatcher/registry/ControllerRegistry;Lio/katharsis/errorhandling/mapper/ExceptionMapperRegistry;Lio/katharsis/queryspec/internal/QueryAdapterBuilder;)V
	at io.katharsis.rs.KatharsisFeature.createRequestDispatcher(KatharsisFeature.java:208)
	at io.katharsis.rs.KatharsisFeature.configure(KatharsisFeature.java:147)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProviderInstance(ResteasyProviderFactory.java:2087)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProviderInstance(ResteasyProviderFactory.java:1758)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.register(ResteasyProviderFactory.java:2445)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.register(ResteasyProviderFactory.java:99)
	at org.jboss.resteasy.util.FeatureContextDelegate.register(FeatureContextDelegate.java:65)
	at org.jboss.resteasy.util.FeatureContextDelegate.register(FeatureContextDelegate.java:12)
	at org.ddg.DDGRestAPI.service.KatharsisFeature.configure(KatharsisFeature.java:66)
	at org.ddg.DDGRestAPI.service.KatharsisFeature$Proxy$_$$_WeldClientProxy.configure(Unknown Source)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProvider(ResteasyProviderFactory.java:1739)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProvider(ResteasyProviderFactory.java:1368)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProvider(ResteasyProviderFactory.java:1290)
	at org.jboss.resteasy.spi.ResteasyDeployment.registerProvider(ResteasyDeployment.java:571)
	at org.jboss.resteasy.spi.ResteasyDeployment.registration(ResteasyDeployment.java:347)
	at org.jboss.resteasy.spi.ResteasyDeployment.start(ResteasyDeployment.java:250)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.init(ServletContainerDispatcher.java:113)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.init(HttpServletDispatcher.java:36)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:117)
	at org.wildfly.extension.undertow.security.RunAsLifecycleInterceptor.init(RunAsLifecycleInterceptor.java:78)
	at io.undertow.servlet.core.LifecyleInterceptorInvocation.proceed(LifecyleInterceptorInvocation.java:103)
	at io.undertow.servlet.core.ManagedServlet$DefaultInstanceStrategy.start(ManagedServlet.java:250)
	at io.undertow.servlet.core.ManagedServlet.createServlet(ManagedServlet.java:133)
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:546)
	at io.undertow.servlet.core.DeploymentManagerImpl$2.call(DeploymentManagerImpl.java:517)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:42)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.api.LegacyThreadSetupActionWrapper$1.call(LegacyThreadSetupActionWrapper.java:44)
	at io.undertow.servlet.core.DeploymentManagerImpl.start(DeploymentManagerImpl.java:559)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService.startContext(UndertowDeploymentService.java:101)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentService$1.run(UndertowDeploymentService.java:82)
	... 6 more

12:07:37,330 ERROR [org.jboss.as.controller.management-operation] (management-handler-thread - 1) WFLYCTL0013: Operation ("deploy") failed - address: ([("deployment" => "DDGRestAPI.war")]) - failure description: {
    "WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host./DDGRestAPI" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./DDGRestAPI: java.lang.NoSuchMethodError: io.katharsis.dispatcher.RequestDispatcher.<init>(Lio/katharsis/module/ModuleRegistry;Lio/katharsis/dispatcher/registry/ControllerRegistry;Lio/katharsis/errorhandling/mapper/ExceptionMapperRegistry;Lio/katharsis/queryspec/internal/QueryAdapterBuilder;)V
    Caused by: java.lang.NoSuchMethodError: io.katharsis.dispatcher.RequestDispatcher.<init>(Lio/katharsis/module/ModuleRegistry;Lio/katharsis/dispatcher/registry/ControllerRegistry;Lio/katharsis/errorhandling/mapper/ExceptionMapperRegistry;Lio/katharsis/queryspec/internal/QueryAdapterBuilder;)V"},
    "WFLYCTL0412: Required services that are not installed:" => ["jboss.undertow.deployment.default-server.default-host./DDGRestAPI"],
    "WFLYCTL0180: Services with missing/unavailable dependencies" => undefined
}
12:07:37,331 ERROR [org.jboss.as.server] (management-handler-thread - 1) WFLYSRV0021: Deploy of deployment "DDGRestAPI.war" was rolled back with the following failure message: 
{
    "WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host./DDGRestAPI" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./DDGRestAPI: java.lang.NoSuchMethodError: io.katharsis.dispatcher.RequestDispatcher.<init>(Lio/katharsis/module/ModuleRegistry;Lio/katharsis/dispatcher/registry/ControllerRegistry;Lio/katharsis/errorhandling/mapper/ExceptionMapperRegistry;Lio/katharsis/queryspec/internal/QueryAdapterBuilder;)V
    Caused by: java.lang.NoSuchMethodError: io.katharsis.dispatcher.RequestDispatcher.<init>(Lio/katharsis/module/ModuleRegistry;Lio/katharsis/dispatcher/registry/ControllerRegistry;Lio/katharsis/errorhandling/mapper/ExceptionMapperRegistry;Lio/katharsis/queryspec/internal/QueryAdapterBuilder;)V"},
    "WFLYCTL0412: Required services that are not installed:" => ["jboss.undertow.deployment.default-server.default-host./DDGRestAPI"],
    "WFLYCTL0180: Services with missing/unavailable dependencies" => undefined
}
12:07:37,443 INFO  [org.jboss.as.server.deployment] (MSC service thread 1-5) WFLYSRV0028: Stopped deployment DDGRestAPI.war (runtime-name: DDGRestAPI.war) in 111ms
12:07:37,443 INFO  [org.jboss.as.controller] (management-handler-thread - 1) WFLYCTL0183: Service status report
WFLYCTL0186:   Services which failed to start:      service jboss.undertow.deployment.default-server.default-host./DDGRestAPI

[2016-10-24 12:07:37,487] Artifact DDGRestAPI:war: Error during artifact deployment. See server log for details.
[2016-10-24 12:07:37,491] Artifact DDGRestAPI:war: java.lang.Exception: {"WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host./DDGRestAPI" => "org.jboss.msc.service.StartException in service jboss.undertow.deployment.default-server.default-host./DDGRestAPI: java.lang.NoSuchMethodError: io.katharsis.dispatcher.RequestDispatcher.<init>(Lio/katharsis/module/ModuleRegistry;Lio/katharsis/dispatcher/registry/ControllerRegistry;Lio/katharsis/errorhandling/mapper/ExceptionMapperRegistry;Lio/katharsis/queryspec/internal/QueryAdapterBuilder;)V
    Caused by: java.lang.NoSuchMethodError: io.katharsis.dispatcher.RequestDispatcher.<init>(Lio/katharsis/module/ModuleRegistry;Lio/katharsis/dispatcher/registry/ControllerRegistry;Lio/katharsis/errorhandling/mapper/ExceptionMapperRegistry;Lio/katharsis/queryspec/internal/QueryAdapterBuilder;)V"},"WFLYCTL0412: Required services that are not installed:" => ["jboss.undertow.deployment.default-server.default-host./DDGRestAPI"],"WFLYCTL0180: Services with missing/unavailable dependencies" => undefined}

```

It seems I'm missing some dependencies?

**Comment by mohlek** [comment]
Ah found my error. I switched to IntelliJ recently and didn't setup my environment correctly.

**Comment by chb0github** [comment]
Well, the problem is/was that class didn't have a default constructor. I was considering adding it (as it's no real harm). But since you found the issue there is no need.

**Comment by mohlek** [comment]
Yeah, katharsis starts now but the trouble does on :D
I have a few custom routes working with jax-rs @PATH.
They don't work anymore. But I may open a separate issue for this

**Comment by chb0github** [comment]
Let me have a look later today.

**Comment by chb0github** [comment]
Does the example start
