### ISSUE TITLE
Improve reflection error messages in JpaResourceInformationBuilder.java

### ISSUE THREAD

**Issue by Ramblurr** [katharsis-project/katharsis-framework#257]
I had to wade through quite a few `NoSuchFieldException` when getting started with katharsis-jpa.

Errors like:
```
Caused by: java.lang.NoSuchFieldException: someFieldName
	at java.lang.Class.getDeclaredField(Class.java:2070)
	at io.katharsis.jpa.internal.JpaResourceInformationBuilder.toField(JpaResourceInformationBuilder.java:272)
```

It would make troubleshooting much easier if the class name was included in the error message.

**Comment by remmeier** [comment]
that code no longer exists
