### ISSUE TITLE
Missing example of using @HeaderParam or @CookieParam inside a @JsonApiResourceRepository

### ISSUE THREAD

**Issue by yuvalbo** [katharsis-project/katharsis-framework#270]
Hi
We are starting to use Katharsis as our REST framework.
I noticed there is JAX-RS but I am really missing an example of how we should use it in our `@JsonApiResourceRepository` implementations.

Help is much appriciated

**Comment by chb0github** [comment]
I don't understand your question. There are tons of examples in the code
base (more than I would prefer, even).

**Comment by yuvalbo** [comment]
@chb0github I am using Spring-Boot, seems that there is a missing configuration to be set in order for Katharsis  to accept `@HeaderParam`

This is my code snippet 
```
@Component
@JsonApiResourceRepository(Tag.class)
public class TagResourceRepository {

    @JsonApiFindOne
    public Tag findOne(Integer taskId, @HeaderParam("x-test") String header) {
```

I have 
```
    compile group: 'io.katharsis', name: 'katharsis-spring', version: '2.8.2'
    compile group: 'io.katharsis', name: 'katharsis-core', version: '2.8.2'
    compile group: 'io.katharsis', name: 'katharsis-rs', version: '2.8.2'
```
On my Gradle build file.

I also have:

```
@Import(KatharsisConfigV3.class)
@RestController
public class KatharsisController {

    private ResourceRegistry resourceRegistry;

    KatharsisController(ResourceRegistry registry) {
        resourceRegistry = registry;
    }

    @RequestMapping("/resourcesInfo")
    public Map<?, ?> getResources() {
        Map<String, String> result = new HashMap<>();
        // Add all resources (i.e. Project and Task)
        for (Class<?> clazz : resourceRegistry.getResources().keySet()) {
            result.put(resourceRegistry.getResourceType(clazz), resourceRegistry.getResourceUrl(clazz));
        }
        return result;
    }

}
```

But I am getting the following error when I try to access /tags/123
```

Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Name for argument type [java.lang.String] not available, and parameter name information not found in class file either.
	at io.katharsis.spring.SpringParameterProvider.provide(SpringParameterProvider.java:97) ~[katharsis-spring-2.8.2.jar:na]
	at io.katharsis.repository.ParametersFactory.buildParameters(ParametersFactory.java:47) ~[katharsis-core-2.8.2.jar:na]
	at io.katharsis.repository.annotated.AnnotatedRepositoryAdapter.invokeOperation(AnnotatedRepositoryAdapter.java:93) ~[katharsis-core-2.8.2.jar:na]
	at io.katharsis.repository.annotated.AnnotatedResourceRepositoryAdapter.findOne(AnnotatedResourceRepositoryAdapter.java:38) ~[katharsis-core-2.8.2.jar:na]
	at io.katharsis.resource.registry.repository.adapter.ResourceRepositoryAdapter$1.invoke(ResourceRepositoryAdapter.java:46) ~[katharsis-core-2.8.2.jar:na]
	at io.katharsis.resource.registry.repository.adapter.ResponseRepositoryAdapter$RepositoryRequestFilterChainImpl.doFilter(ResponseRepositoryAdapter.java:210) ~[katharsis-core-2.8.2.jar:na]
	at io.katharsis.resource.registry.repository.adapter.ResourceRepositoryAdapter.findOne(ResourceRepositoryAdapter.java:61) ~[katharsis-core-2.8.2.jar:na]
	at io.katharsis.dispatcher.controller.resource.ResourceGet.handle(ResourceGet.java:63) ~[katharsis-core-2.8.2.jar:na]
	at io.katharsis.dispatcher.RequestDispatcher$DefaultFilterChain.doFilter(RequestDispatcher.java:129) ~[katharsis-core-2.8.2.jar:na]
	at io.katharsis.dispatcher.RequestDispatcher.dispatchRequest(RequestDispatcher.java:80) ~[katharsis-core-2.8.2.jar:na]
	at io.katharsis.spring.KatharsisFilterV2.dispatchRequest(KatharsisFilterV2.java:128) ~[katharsis-spring-2.8.2.jar:na]
	at io.katharsis.spring.KatharsisFilterV2.invoke(KatharsisFilterV2.java:102) ~[katharsis-spring-2.8.2.jar:na]
	... 77 common frames omitted
Caused by: java.lang.IllegalArgumentException: Name for argument type [java.lang.String] not available, and parameter name information not found in class file either.
	at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.updateNamedValueInfo(AbstractNamedValueMethodArgumentResolver.java:167) ~[spring-web-5.0.0.BUILD-SNAPSHOT.jar:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.getNamedValueInfo(AbstractNamedValueMethodArgumentResolver.java:144) ~[spring-web-5.0.0.BUILD-SNAPSHOT.jar:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.resolveArgument(AbstractNamedValueMethodArgumentResolver.java:93) ~[spring-web-5.0.0.BUILD-SNAPSHOT.jar:5.0.0.BUILD-SNAPSHOT]
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:121) ~[spring-web-5.0.0.BUILD-SNAPSHOT.jar:5.0.0.BUILD-SNAPSHOT]
	at io.katharsis.spring.SpringParameterProvider.provide(SpringParameterProvider.java:95) ~[katharsis-spring-2.8.2.jar:na]
	... 88 common frames omitted
```

I am guessing that something needs to "tell" spring not to use the default filter but the one supporting Jax-RS but I haven't found the setup.

Any link/help is more than appreciated.
These are the examples I have been looking at:
[https://github.com/katharsis-project/katharsis-framework/tree/master/katharsis-examples](url)

**Comment by yuvalbo** [comment]
@Ramblurr Happy holidays (I hope marking it as question doesn't mean it will be left open ;) )

**Comment by chb0github** [comment]
What you're trying to do isn't programmed into katharsis at all. If you need header params, the ONLY way to do it is:

```
@Component
public class SomeRepository  {
       @Resource
    protected HttpServletRequest request;

    public SomeRepository() {
        String host = request.getHeader("host");
        
    }
}
```

Then this becomes a thread-local variable. 

The ONLY way this could be made to work is if Katharsis went with just an annotated approach to repositories; then you could do as you suggested.

I have inherited this project and there are some definite short comings. Perhaps the thing to do is upgrade the annotated support to allow this, mark the interface method as deprecated and continue to pile code into the Annotated process such that users continue to switch to gain features?

**Comment by yuvalbo** [comment]
@chb0github Thank you for the prompt answer and happy holidays.
I am referring to katharsis-rs

See: https://github.com/katharsis-project/katharsis-framework/blob/master/katharsis-rs/src/test/java/io/katharsis/rs/resource/repository/TaskRepository.java

Specifically:

```
 @JsonApiFindOne
    public Task findOne(Long aLong, @HeaderParam("x-test") String header) {
        // Simulates error and throws an Exception to test exception handling.
        if (aLong == 5) {
            throw new ExampleException(ExampleException.ERROR_ID, ExampleException.ERROR_TITLE);
        }
        Task task = new Task(aLong, header);
        return task;
    }
```

What should one set up using spring-boot for this to work?
