### ISSUE TITLE
War deployment with katharsis-cdi dependency fails on TomEE 7.0.2

### ISSUE THREAD

**Issue by Sandmania** [katharsis-project/katharsis-framework#280]
- katharsis-cdi:2.8.2
- tomee:7.0.2

Steps to reproduce:

1. Create a simple war, with katharsis-cdi 2.8.2 as a dependency (Or clone this one https://github.com/Sandmania/katharsis-cdi-bug)
2. Download and extract TomEE 7.0.2 plus http://repo.maven.apache.org/maven2/org/apache/tomee/apache-tomee/7.0.2/apache-tomee-7.0.2-plus.tar.gz
3. Start TomEE by running {tomee_dir}/bin/startup.sh
4. Deploy war from step 1 by copying it to {tomee_dir}/webapps

Expected result: War is deployed without errors

Actual result: The following stacktrace

```
02-Jan-2017 14:55:18.969 INFO [localhost-startStop-2] sun.reflect.DelegatingMethodAccessorImpl.invoke Deploying web application archive /Users/jounilatvatalo/hobby/servers/apache-tomee-plus-7.0.2/webapps/katharsis-cdi-bug-0.1.war
02-Jan-2017 14:55:18.969 INFO [localhost-startStop-2] org.apache.tomee.catalina.TomcatWebAppBuilder.init ------------------------- localhost -> /katharsis-cdi-bug-0.1
02-Jan-2017 14:55:18.971 INFO [localhost-startStop-2] org.apache.openejb.util.JarExtractor.extract Extracting jar: /Users/jounilatvatalo/hobby/servers/apache-tomee-plus-7.0.2/webapps/katharsis-cdi-bug-0.1.war
02-Jan-2017 14:55:19.011 INFO [localhost-startStop-2] org.apache.openejb.util.JarExtractor.extract Extracted path: /Users/jounilatvatalo/hobby/servers/apache-tomee-plus-7.0.2/webapps/katharsis-cdi-bug-0.1
02-Jan-2017 14:55:19.449 INFO [localhost-startStop-2] org.apache.openejb.config.ConfigurationFactory.configureApplication Configuring enterprise application: /Users/jounilatvatalo/hobby/servers/apache-tomee-plus-7.0.2/webapps/katharsis-cdi-bug-0.1
02-Jan-2017 14:55:19.529 INFO [localhost-startStop-2] org.apache.openejb.config.ConfigurationFactory.configureService Configuring Service(id=Default Managed Container, type=Container, provider-id=Default Managed Container)
02-Jan-2017 14:55:19.529 INFO [localhost-startStop-2] org.apache.openejb.config.AutoConfig.createContainer Auto-creating a container for bean katharsis-cdi-bug-0.1/katharsis-cdi-bug-0.1.Comp281038048: Container(type=MANAGED, id=Default Managed Container)
02-Jan-2017 14:55:19.529 INFO [localhost-startStop-2] org.apache.openejb.assembler.classic.Assembler.createRecipe Creating Container(id=Default Managed Container)
02-Jan-2017 14:55:19.544 INFO [localhost-startStop-2] org.apache.openejb.core.managed.SimplePassivater.init Using directory /Users/jounilatvatalo/hobby/servers/apache-tomee-plus-7.0.2/temp for stateful session passivation
02-Jan-2017 14:55:19.565 INFO [localhost-startStop-2] org.apache.openejb.util.OptionsLog.info Using 'openejb.validation.output.level=VERBOSE'
02-Jan-2017 14:55:19.577 WARNING [localhost-startStop-2] org.apache.openejb.config.ReportValidationResults.logResults WARN ... WebModule{moduleId='katharsis-cdi-bug-0.1', contextRoot='katharsis-cdi-bug-0.1'}:Incorrect location of file file:/Users/jounilatvatalo/hobby/servers/apache-tomee-plus-7.0.2/webapps/katharsis-cdi-bug-0.1/META-INF/beans.xml The file should be in WEB-INF directory
02-Jan-2017 14:55:19.577 WARNING [localhost-startStop-2] org.apache.openejb.config.ReportValidationResults.logResults 1 warning for WebModule(path=katharsis-cdi-bug-0.1)
02-Jan-2017 14:55:19.578 INFO [localhost-startStop-2] org.apache.openejb.config.AppInfoBuilder.build Enterprise application "/Users/jounilatvatalo/hobby/servers/apache-tomee-plus-7.0.2/webapps/katharsis-cdi-bug-0.1" loaded.
02-Jan-2017 14:55:19.578 INFO [localhost-startStop-2] org.apache.openejb.assembler.classic.Assembler.createApplication Assembling app: /Users/jounilatvatalo/hobby/servers/apache-tomee-plus-7.0.2/webapps/katharsis-cdi-bug-0.1
02-Jan-2017 14:55:19.644 INFO [localhost-startStop-2] org.apache.openejb.cdi.CdiBuilder.initSingleton Existing thread singleton service in SystemInstance(): org.apache.openejb.cdi.ThreadSingletonServiceImpl@6692b6c6
02-Jan-2017 14:55:19.762 INFO [localhost-startStop-2] org.apache.openejb.cdi.OpenEJBLifecycle.startApplication OpenWebBeans Container is starting...
02-Jan-2017 14:55:19.777 INFO [localhost-startStop-2] org.apache.webbeans.plugins.PluginLoader.startUp Adding OpenWebBeansPlugin : [CdiPlugin]
02-Jan-2017 14:55:19.783 INFO [localhost-startStop-2] org.apache.openejb.cdi.CdiScanner.handleBda Using annotated mode for jar:file:/Users/jounilatvatalo/hobby/servers/apache-tomee-plus-7.0.2/webapps/katharsis-cdi-bug-0.1/WEB-INF/lib/katharsis-cdi-2.8.2.jar!/META-INF/beans.xml looking all classes to find CDI beans, maybe think to add a beans.xml if not there or add the jar to exclusions.list
02-Jan-2017 14:55:20.129 SEVERE [localhost-startStop-2] org.apache.openejb.cdi.OpenEJBLifecycle.startApplication CDI Beans module deployment failed
 org.apache.webbeans.exception.WebBeansDeploymentException: javax.enterprise.inject.UnproxyableResolutionException: WebBeans with api type with normal scope must be proxyable.
io.katharsis.cdi.internal.CdiTransactionRunner has no explicit no-arg constructor!A public or protected constructor without args is required!
	at org.apache.webbeans.config.BeansDeployer.deploy(BeansDeployer.java:336)
	at org.apache.openejb.cdi.OpenEJBLifecycle.startApplication(OpenEJBLifecycle.java:196)
	at org.apache.openejb.cdi.ThreadSingletonServiceImpl.initialize(ThreadSingletonServiceImpl.java:189)
	at org.apache.openejb.cdi.CdiBuilder.build(CdiBuilder.java:41)
	at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:913)
	at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:717)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.startInternal(TomcatWebAppBuilder.java:1298)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.configureStart(TomcatWebAppBuilder.java:1124)
	at org.apache.tomee.catalina.GlobalListenerSupport.lifecycleEvent(GlobalListenerSupport.java:133)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5087)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.enterprise.inject.UnproxyableResolutionException: WebBeans with api type with normal scope must be proxyable.
io.katharsis.cdi.internal.CdiTransactionRunner has no explicit no-arg constructor!A public or protected constructor without args is required!
	at org.apache.webbeans.util.InjectionExceptionUtil.createUnproxyableResolutionException(InjectionExceptionUtil.java:46)
	at org.apache.webbeans.util.InjectionExceptionUtil.throwUnproxyableResolutionException(InjectionExceptionUtil.java:41)
	at org.apache.webbeans.config.DeploymentValidationService.validateProxyable(DeploymentValidationService.java:143)
	at org.apache.webbeans.component.creation.ManagedBeanBuilder.getBean(ManagedBeanBuilder.java:70)
	at org.apache.webbeans.config.BeansDeployer.defineManagedBean(BeansDeployer.java:1645)
	at org.apache.webbeans.config.BeansDeployer.deploySingleAnnotatedType(BeansDeployer.java:1271)
	at org.apache.webbeans.config.BeansDeployer.deployFromBeanAttributes(BeansDeployer.java:1227)
	at org.apache.webbeans.config.BeansDeployer.deploy(BeansDeployer.java:295)
	... 21 more

02-Jan-2017 14:55:20.129 SEVERE [localhost-startStop-2] org.apache.tomee.catalina.TomcatWebAppBuilder.startInternal Unable to deploy collapsed ear in war StandardEngine[Catalina].StandardHost[localhost].StandardContext[/katharsis-cdi-bug-0.1]
 javax.enterprise.inject.spi.DeploymentException: couldn't start owb context
	at org.apache.openejb.cdi.ThreadSingletonServiceImpl.initialize(ThreadSingletonServiceImpl.java:191)
	at org.apache.openejb.cdi.CdiBuilder.build(CdiBuilder.java:41)
	at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:913)
	at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:717)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.startInternal(TomcatWebAppBuilder.java:1298)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.configureStart(TomcatWebAppBuilder.java:1124)
	at org.apache.tomee.catalina.GlobalListenerSupport.lifecycleEvent(GlobalListenerSupport.java:133)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5087)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.openejb.OpenEJBRuntimeException: org.apache.webbeans.exception.WebBeansDeploymentException: javax.enterprise.inject.UnproxyableResolutionException: WebBeans with api type with normal scope must be proxyable.
io.katharsis.cdi.internal.CdiTransactionRunner has no explicit no-arg constructor!A public or protected constructor without args is required!
	at org.apache.openejb.cdi.OpenEJBLifecycle.startApplication(OpenEJBLifecycle.java:200)
	at org.apache.openejb.cdi.ThreadSingletonServiceImpl.initialize(ThreadSingletonServiceImpl.java:189)
	... 19 more
Caused by: org.apache.webbeans.exception.WebBeansDeploymentException: javax.enterprise.inject.UnproxyableResolutionException: WebBeans with api type with normal scope must be proxyable.
io.katharsis.cdi.internal.CdiTransactionRunner has no explicit no-arg constructor!A public or protected constructor without args is required!
	at org.apache.webbeans.config.BeansDeployer.deploy(BeansDeployer.java:336)
	at org.apache.openejb.cdi.OpenEJBLifecycle.startApplication(OpenEJBLifecycle.java:196)
	... 20 more
Caused by: javax.enterprise.inject.UnproxyableResolutionException: WebBeans with api type with normal scope must be proxyable.
io.katharsis.cdi.internal.CdiTransactionRunner has no explicit no-arg constructor!A public or protected constructor without args is required!
	at org.apache.webbeans.util.InjectionExceptionUtil.createUnproxyableResolutionException(InjectionExceptionUtil.java:46)
	at org.apache.webbeans.util.InjectionExceptionUtil.throwUnproxyableResolutionException(InjectionExceptionUtil.java:41)
	at org.apache.webbeans.config.DeploymentValidationService.validateProxyable(DeploymentValidationService.java:143)
	at org.apache.webbeans.component.creation.ManagedBeanBuilder.getBean(ManagedBeanBuilder.java:70)
	at org.apache.webbeans.config.BeansDeployer.defineManagedBean(BeansDeployer.java:1645)
	at org.apache.webbeans.config.BeansDeployer.deploySingleAnnotatedType(BeansDeployer.java:1271)
	at org.apache.webbeans.config.BeansDeployer.deployFromBeanAttributes(BeansDeployer.java:1227)
	at org.apache.webbeans.config.BeansDeployer.deploy(BeansDeployer.java:295)
	... 21 more

02-Jan-2017 14:55:20.130 SEVERE [localhost-startStop-2] sun.reflect.NativeMethodAccessorImpl.invoke ContainerBase.removeChild: destroy:
 org.apache.catalina.LifecycleException: An invalid Lifecycle transition was attempted ([before_destroy]) for component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/katharsis-cdi-bug-0.1]] in state [STARTING_PREP]
	at org.apache.catalina.util.LifecycleBase.invalidTransition(LifecycleBase.java:402)
	at org.apache.catalina.util.LifecycleBase.destroy(LifecycleBase.java:292)
	at org.apache.catalina.core.ContainerBase.removeChild(ContainerBase.java:826)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.undeploy(TomcatWebAppBuilder.java:1627)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.undeploy(TomcatWebAppBuilder.java:1607)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.startInternal(TomcatWebAppBuilder.java:1307)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.configureStart(TomcatWebAppBuilder.java:1124)
	at org.apache.tomee.catalina.GlobalListenerSupport.lifecycleEvent(GlobalListenerSupport.java:133)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5087)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

02-Jan-2017 14:55:20.132 SEVERE [localhost-startStop-2] sun.reflect.NativeMethodAccessorImpl.invoke ContainerBase.addChild: start:
 org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/katharsis-cdi-bug-0.1]]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:167)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:724)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.tomee.catalina.TomEERuntimeException: javax.enterprise.inject.spi.DeploymentException: couldn't start owb context
	at org.apache.tomee.catalina.TomcatWebAppBuilder.startInternal(TomcatWebAppBuilder.java:1310)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.configureStart(TomcatWebAppBuilder.java:1124)
	at org.apache.tomee.catalina.GlobalListenerSupport.lifecycleEvent(GlobalListenerSupport.java:133)
	at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:94)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5087)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	... 10 more
Caused by: javax.enterprise.inject.spi.DeploymentException: couldn't start owb context
	at org.apache.openejb.cdi.ThreadSingletonServiceImpl.initialize(ThreadSingletonServiceImpl.java:191)
	at org.apache.openejb.cdi.CdiBuilder.build(CdiBuilder.java:41)
	at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:913)
	at org.apache.openejb.assembler.classic.Assembler.createApplication(Assembler.java:717)
	at org.apache.tomee.catalina.TomcatWebAppBuilder.startInternal(TomcatWebAppBuilder.java:1298)
	... 15 more
Caused by: org.apache.openejb.OpenEJBRuntimeException: org.apache.webbeans.exception.WebBeansDeploymentException: javax.enterprise.inject.UnproxyableResolutionException: WebBeans with api type with normal scope must be proxyable.
io.katharsis.cdi.internal.CdiTransactionRunner has no explicit no-arg constructor!A public or protected constructor without args is required!
	at org.apache.openejb.cdi.OpenEJBLifecycle.startApplication(OpenEJBLifecycle.java:200)
	at org.apache.openejb.cdi.ThreadSingletonServiceImpl.initialize(ThreadSingletonServiceImpl.java:189)
	... 19 more
Caused by: org.apache.webbeans.exception.WebBeansDeploymentException: javax.enterprise.inject.UnproxyableResolutionException: WebBeans with api type with normal scope must be proxyable.
io.katharsis.cdi.internal.CdiTransactionRunner has no explicit no-arg constructor!A public or protected constructor without args is required!
	at org.apache.webbeans.config.BeansDeployer.deploy(BeansDeployer.java:336)
	at org.apache.openejb.cdi.OpenEJBLifecycle.startApplication(OpenEJBLifecycle.java:196)
	... 20 more
Caused by: javax.enterprise.inject.UnproxyableResolutionException: WebBeans with api type with normal scope must be proxyable.
io.katharsis.cdi.internal.CdiTransactionRunner has no explicit no-arg constructor!A public or protected constructor without args is required!
	at org.apache.webbeans.util.InjectionExceptionUtil.createUnproxyableResolutionException(InjectionExceptionUtil.java:46)
	at org.apache.webbeans.util.InjectionExceptionUtil.throwUnproxyableResolutionException(InjectionExceptionUtil.java:41)
	at org.apache.webbeans.config.DeploymentValidationService.validateProxyable(DeploymentValidationService.java:143)
	at org.apache.webbeans.component.creation.ManagedBeanBuilder.getBean(ManagedBeanBuilder.java:70)
	at org.apache.webbeans.config.BeansDeployer.defineManagedBean(BeansDeployer.java:1645)
	at org.apache.webbeans.config.BeansDeployer.deploySingleAnnotatedType(BeansDeployer.java:1271)
	at org.apache.webbeans.config.BeansDeployer.deployFromBeanAttributes(BeansDeployer.java:1227)
	at org.apache.webbeans.config.BeansDeployer.deploy(BeansDeployer.java:295)
	... 21 more

02-Jan-2017 14:55:20.132 SEVERE [localhost-startStop-2] sun.reflect.NativeMethodAccessorImpl.invoke Error deploying web application archive /Users/jounilatvatalo/hobby/servers/apache-tomee-plus-7.0.2/webapps/katharsis-cdi-bug-0.1.war
 java.lang.IllegalStateException: ContainerBase.addChild: start: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Catalina].StandardHost[localhost].StandardContext[/katharsis-cdi-bug-0.1]]
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:728)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:700)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:952)
	at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1823)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

02-Jan-2017 14:55:20.134 INFO [localhost-startStop-2] sun.reflect.DelegatingMethodAccessorImpl.invoke Deployment of web application archive /Users/jounilatvatalo/hobby/servers/apache-tomee-plus-7.0.2/webapps/katharsis-cdi-bug-0.1.war has finished in 1,165 ms
```

**Comment by Sandmania** [comment]
Fixed by https://github.com/katharsis-project/katharsis-framework/pull/282
