### ISSUE TITLE
Katharsis unable to serialize/deserialize enums

### ISSUE THREAD

**Issue by ealexhaywood** [katharsis-project/katharsis-framework#333]
Hi,

We have a POJO that has an enum as a field.  Katharsis is unable to handle it for some reason.  Katharsis throws a `NoSuchElementException` when I try to access the object that contains an enum field.  Below is the stacktrace:

``` 
Caused by: com.fasterxml.jackson.databind.JsonMappingException: No value present
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:303) ~[jackson-databind-2.8.4.jar:2.8.4]
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3681) ~[jackson-databind-2.8.4.jar:2.8.4]
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:3014) ~[jackson-databind-2.8.4.jar:2.8.4]
	at io.katharsis.spring.KatharsisFilterV2.dispatchRequest(KatharsisFilterV2.java:155) ~[katharsis-spring-1.0.0.jar:na]
	at io.katharsis.spring.KatharsisFilterV2.invoke(KatharsisFilterV2.java:106) ~[katharsis-spring-1.0.0.jar:na]
	... 40 common frames omitted
Caused by: java.util.NoSuchElementException: No value present
	at io.katharsis.utils.java.Optional.get(Optional.java:21) ~[katharsis-core-1.0.0.jar:na]
	at io.katharsis.jackson.serializer.include.IncludedRelationshipExtractor.getResourceDigest(IncludedRelationshipExtractor.java:124) ~[katharsis-core-1.0.0.jar:na]
	at io.katharsis.jackson.serializer.include.IncludedRelationshipExtractor.populateIncludedResources(IncludedRelationshipExtractor.java:72) ~[katharsis-core-1.0.0.jar:na]
	at io.katharsis.jackson.serializer.include.IncludedRelationshipExtractor.extractIncludedResources(IncludedRelationshipExtractor.java:44) ~[katharsis-core-1.0.0.jar:na]
	at io.katharsis.jackson.serializer.BaseResponseSerializer.serializeResourceCollection(BaseResponseSerializer.java:121) ~[katharsis-core-1.0.0.jar:na]
	at io.katharsis.jackson.serializer.BaseResponseSerializer.writeResponseWithResources(BaseResponseSerializer.java:88) ~[katharsis-core-1.0.0.jar:na]
	at io.katharsis.jackson.serializer.BaseResponseSerializer.serialize(BaseResponseSerializer.java:50) ~[katharsis-core-1.0.0.jar:na]
	at io.katharsis.jackson.serializer.BaseResponseSerializer.serialize(BaseResponseSerializer.java:27) ~[katharsis-core-1.0.0.jar:na]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:292) ~[jackson-databind-2.8.4.jar:2.8.4]
```

For reference, here is the enum that is used as a field in the said POJO:

```
  public enum ExecutionStatus {
    CREATED(true), SUBMITTED(true), QUEUED(true), STARTED(true), STOPPED(false), FAILED(false), PARTIAL_FAILED(true);

    private boolean running;

    ExecutionStatus(boolean running) {
        this.running = running;
    }

    public boolean isRunning() {
        return running;
    }

    public void setRunning(boolean running) {
        this.running = running;
    }
}
``` 

It may have something to do with some of the enums sharing values (true/false).  However, Spring has no problem with this.

**Comment by remmeier** [comment]
not sure, you want to look at the develop_v3 branch with the upcoming 3.0 version. That part has been completely rewritten in the meantime.

**Comment by chb0github** [comment]
can you create a branch from master that duplicates this issue? Include a curl comand

**Comment by chb0github** [comment]
As a total aside: Using state transition is the way to handle this:

```
public enum ExecutionStatus {
   
   public abstract ExecutionStatus start();

  STOPPED(false) {

     public ExecutionStatus start() {
        return RUNNING;
     }
   }
}
```


Instead of `setStatus` - [check out this](http://codereview.stackexchange.com/questions/43075/modularize-more-efficiently-in-an-if-else-setup/43311#43311)

**Comment by ealexhaywood** [comment]
Sorry this was user error.  One of our resources did not have a registered `ResourceRepository` but had a relationship associated with it.  This had nothing to do with enumerations.

**Comment by chb0github** [comment]
Glad to hear it. Hence the reason we ask for a simple example.
