### ISSUE TITLE
Use custom ID types

### ISSUE THREAD

**Issue by exports** [katharsis-project/katharsis-framework#359]
Hi there!
I'm using java.util.UUID as the id type and use hibernate to auto-generate its value, but when I create a resource, it returns id: null. Do I miss any configuration?

version: katharsis-jpa 2.8.2

**Comment by mohlek** [comment]
Could you provide any code? At least the entity class?

**Comment by exports** [comment]
Example entity class

```
@Entity
public class User {

    @Id
    @GeneratedValue(generator = "uuid")
    @GenericGenerator(name = "uuid", strategy = "uuid2")
    private UUID id;
}
```

**Comment by remmeier** [comment]
you may want to check whether https://github.com/katharsis-project/katharsis-framework/pull/363 fixes this as well

**Comment by remmeier** [comment]
reopen otherwise

**Comment by Coronel-B** [comment]
```
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: all
	at java.util.UUID.fromString(UUID.java:194) ~[na:1.8.0_272]
	at io.katharsis.utils.parser.DefaultStringParsers$11.parse(DefaultStringParsers.java:96) ~[katharsis-core-3.0.2.jar:na]
	at io.katharsis.utils.parser.DefaultStringParsers$11.parse(DefaultStringParsers.java:93) ~[katharsis-core-3.0.2.jar:na]
	at io.katharsis.utils.parser.TypeParser.parseInput(TypeParser.java:100) ~[katharsis-core-3.0.2.jar:na]
	at io.katharsis.utils.parser.TypeParser.parse(TypeParser.java:87) ~[katharsis-core-3.0.2.jar:na]
	at io.katharsis.core.internal.dispatcher.controller.ResourceGet.handle(ResourceGet.java:58) ~[katharsis-core-3.0.2.jar:na]
	at io.katharsis.core.internal.dispatcher.RequestDispatcher$DefaultFilterChain.doFilter(RequestDispatcher.java:126) ~[katharsis-core-3.0.2.jar:na]
	at io.katharsis.core.internal.dispatcher.RequestDispatcher.dispatchRequest(RequestDispatcher.java:80) ~[katharsis-core-3.0.2.jar:na]
	at io.katharsis.spring.KatharsisFilterV2.dispatchRequest(KatharsisFilterV2.java:131) ~[katharsis-spring-3.0.2.jar:na]
	at io.katharsis.spring.KatharsisFilterV2.invoke(KatharsisFilterV2.java:105) ~[katharsis-spring-3.0.2.jar:na]
```
