### ISSUE TITLE
Meta module load fails, if resources contain multiple List<String> attributes

### ISSUE THREAD

**Issue by Sandmania** [katharsis-project/katharsis-framework#399]
Using meta module from master fails to load if resources contain multiple List<String> attributes.

See PR https://github.com/katharsis-project/katharsis-framework/pull/398 
and build results https://travis-ci.org/katharsis-project/katharsis-framework/builds/218030029
for details.

**Comment by Sandmania** [comment]
As there are some other build problems with travis, here is a snippet from my local build:

```
Running io.katharsis.meta.MetaMetaTest
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 1.452 sec <<< FAILURE! - in io.katharsis.meta.MetaMetaTest
testAttributesProperlyDeclaredAndNotInherited(io.katharsis.meta.MetaMetaTest)  Time elapsed: 1.278 sec  <<< ERROR!
java.lang.IllegalStateException: base.string$List already available: MetaListType[name=string$List] vs MetaListType[name=string$List]
	at io.katharsis.meta.MetaMetaTest.setup(MetaMetaTest.java:29)

testMetaDataObjectMeta(io.katharsis.meta.MetaMetaTest)  Time elapsed: 0.059 sec  <<< ERROR!
java.lang.IllegalStateException: base.string$List already available: MetaListType[name=string$List] vs MetaListType[name=string$List]
	at io.katharsis.meta.MetaMetaTest.setup(MetaMetaTest.java:29)

Running io.katharsis.meta.MetaModuleTest
Tests run: 8, Failures: 0, Errors: 8, Skipped: 0, Time elapsed: 1.047 sec <<< FAILURE! - in io.katharsis.meta.MetaModuleTest
testGetResourceAsMetaElement(io.katharsis.meta.MetaModuleTest)  Time elapsed: 0.586 sec  <<< ERROR!
java.lang.IllegalStateException: base.string$List already available: MetaListType[name=string$List] vs MetaListType[name=string$List]
	at io.katharsis.meta.MetaModuleTest.setUp(MetaModuleTest.java:30)

testFindAll(io.katharsis.meta.MetaModuleTest)  Time elapsed: 0.048 sec  <<< ERROR!
java.lang.IllegalStateException: base.string$List already available: MetaListType[name=string$List] vs MetaListType[name=string$List]
	at io.katharsis.meta.MetaModuleTest.setUp(MetaModuleTest.java:30)

testAttributesHaveType(io.katharsis.meta.MetaModuleTest)  Time elapsed: 0.045 sec  <<< ERROR!
java.lang.IllegalStateException: base.string$List already available: MetaListType[name=string$List] vs MetaListType[name=string$List]
	at io.katharsis.meta.MetaModuleTest.setUp(MetaModuleTest.java:30)

testFetchResourcesWithNestedAttributesAndTypes(io.katharsis.meta.MetaModuleTest)  Time elapsed: 0.046 sec  <<< ERROR!
java.lang.IllegalStateException: base.string$List already available: MetaListType[name=string$List] vs MetaListType[name=string$List]
	at io.katharsis.meta.MetaModuleTest.setUp(MetaModuleTest.java:30)

testAttributesHaveParent(io.katharsis.meta.MetaModuleTest)  Time elapsed: 0.049 sec  <<< ERROR!
java.lang.IllegalStateException: base.string$List already available: MetaListType[name=string$List] vs MetaListType[name=string$List]
	at io.katharsis.meta.MetaModuleTest.setUp(MetaModuleTest.java:30)

testIdPrefix(io.katharsis.meta.MetaModuleTest)  Time elapsed: 0.045 sec  <<< ERROR!
java.lang.IllegalStateException: base.string$List already available: MetaListType[name=string$List] vs MetaListType[name=string$List]
	at io.katharsis.meta.MetaModuleTest.setUp(MetaModuleTest.java:30)

testFetchResourcesWithAttributesAndType(io.katharsis.meta.MetaModuleTest)  Time elapsed: 0.044 sec  <<< ERROR!
java.lang.IllegalStateException: base.string$List already available: MetaListType[name=string$List] vs MetaListType[name=string$List]
	at io.katharsis.meta.MetaModuleTest.setUp(MetaModuleTest.java:30)

testGetResource(io.katharsis.meta.MetaModuleTest)  Time elapsed: 0.05 sec  <<< ERROR!
java.lang.IllegalStateException: base.string$List already available: MetaListType[name=string$List] vs MetaListType[name=string$List]
	at io.katharsis.meta.MetaModuleTest.setUp(MetaModuleTest.java:30)

Running io.katharsis.meta.ResourceMetaProviderTest
Tests run: 7, Failures: 0, Errors: 7, Skipped: 0, Time elapsed: 0.112 sec <<< FAILURE! - in io.katharsis.meta.ResourceMetaProviderTest
testMetaAttribute(io.katharsis.meta.ResourceMetaProviderTest)  Time elapsed: 0.041 sec  <<< ERROR!
java.lang.IllegalStateException: base.string$List already available: MetaListType[name=string$List] vs MetaListType[name=string$List]
	at io.katharsis.meta.ResourceMetaProviderTest.setup(ResourceMetaProviderTest.java:49)

testPrimaryKey(io.katharsis.meta.ResourceMetaProviderTest)  Time elapsed: 0.011 sec  <<< ERROR!
java.lang.IllegalStateException: base.string$List already available: MetaListType[name=string$List] vs MetaListType[name=string$List]
	at io.katharsis.meta.ResourceMetaProviderTest.setup(ResourceMetaProviderTest.java:49)

testLinksAttribute(io.katharsis.meta.ResourceMetaProviderTest)  Time elapsed: 0.013 sec  <<< ERROR!
java.lang.IllegalStateException: base.string$List already available: MetaListType[name=string$List] vs MetaListType[name=string$List]
	at io.katharsis.meta.ResourceMetaProviderTest.setup(ResourceMetaProviderTest.java:49)

testResourceProperties(io.katharsis.meta.ResourceMetaProviderTest)  Time elapsed: 0.013 sec  <<< ERROR!
java.lang.IllegalStateException: base.string$List already available: MetaListType[name=string$List] vs MetaListType[name=string$List]
	at io.katharsis.meta.ResourceMetaProviderTest.setup(ResourceMetaProviderTest.java:49)

testMultiValuedRelation(io.katharsis.meta.ResourceMetaProviderTest)  Time elapsed: 0.01 sec  <<< ERROR!
java.lang.IllegalStateException: base.string$List already available: MetaListType[name=string$List] vs MetaListType[name=string$List]
	at io.katharsis.meta.ResourceMetaProviderTest.setup(ResourceMetaProviderTest.java:49)

testRepository(io.katharsis.meta.ResourceMetaProviderTest)  Time elapsed: 0.012 sec  <<< ERROR!
java.lang.IllegalStateException: base.string$List already available: MetaListType[name=string$List] vs MetaListType[name=string$List]
	at io.katharsis.meta.ResourceMetaProviderTest.setup(ResourceMetaProviderTest.java:49)

testSingleValuedRelation(io.katharsis.meta.ResourceMetaProviderTest)  Time elapsed: 0.011 sec  <<< ERROR!
java.lang.IllegalStateException: base.string$List already available: MetaListType[name=string$List] vs MetaListType[name=string$List]
	at io.katharsis.meta.ResourceMetaProviderTest.setup(ResourceMetaProviderTest.java:49)

Running io.katharsis.meta.TestMultipleMetaForSameType
Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.029 sec <<< FAILURE! - in io.katharsis.meta.TestMultipleMetaForSameType
testAsResource(io.katharsis.meta.TestMultipleMetaForSameType)  Time elapsed: 0.011 sec  <<< ERROR!
java.lang.IllegalStateException: base.string$List already available: MetaListType[name=string$List] vs MetaListType[name=string$List]
	at io.katharsis.meta.TestMultipleMetaForSameType.testAsResource(TestMultipleMetaForSameType.java:45)

testBothConcurrently(io.katharsis.meta.TestMultipleMetaForSameType)  Time elapsed: 0.009 sec  <<< ERROR!
java.lang.IllegalStateException: base.string$List already available: MetaListType[name=string$List] vs MetaListType[name=string$List]
	at io.katharsis.meta.TestMultipleMetaForSameType.testBothConcurrently(TestMultipleMetaForSameType.java:64)
```

**Comment by chb0github** [comment]
We have been having a lot of issues with travis, actually. I will try to have a look at this tomorrow
