### ISSUE TITLE
Getting Started - dropwizard-simple-example can't find resource - broken links

### ISSUE THREAD

**Issue by charlesritchea** [katharsis-project/katharsis-framework#454]
First off, the links in Examples http://katharsis.io/examples are all broken
Secondly, and I know this has been filed, but:

```	<groupId>io.katharsis</groupId>
	<artifactId>spring-boot-simple-example</artifactId>
	<version>3.0.4-SNAPSHOT</version>
	<packaging>jar</packaging>
```
doesn't exist. Needs to be chasnged to 3.0.2
When I try to run dropwizard-simple-example, I get:

```
INFO  [2018-01-18 15:29:32,295] org.eclipse.jetty.util.log: Logging initialized @2000ms to org.eclipse.jetty.util.log.Slf4jLog
INFO  [2018-01-18 15:29:32,397] io.dropwizard.server.SimpleServerFactory: Registering jersey handler with root path prefix: /
INFO  [2018-01-18 15:29:32,399] io.dropwizard.server.SimpleServerFactory: Registering admin handler with root path prefix: /admin
INFO  [2018-01-18 15:29:32,447] io.dropwizard.server.SimpleServerFactory: Registering jersey handler with root path prefix: /
INFO  [2018-01-18 15:29:32,447] io.dropwizard.server.SimpleServerFactory: Registering admin handler with root path prefix: /admin
INFO  [2018-01-18 15:29:32,450] io.dropwizard.server.ServerFactory: Starting DropwizardService
INFO  [2018-01-18 15:29:32,614] org.eclipse.jetty.setuid.SetUIDListener: Opened DropwizardService@46185a1b{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
INFO  [2018-01-18 15:29:32,616] org.eclipse.jetty.server.Server: jetty-9.4.2.v20170220
INFO  [2018-01-18 15:29:33,053] org.reflections.Reflections: Reflections took 111 ms to scan 2 urls, producing 24 keys and 153 values 
INFO  [2018-01-18 15:29:33,414] io.dropwizard.jersey.DropwizardResourceConfig: The following paths were found for the configured resources:

    NONE

INFO  [2018-01-18 15:29:33,415] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@58ff8d79{/,null,AVAILABLE}
INFO  [2018-01-18 15:29:33,424] io.dropwizard.setup.AdminEnvironment: tasks = 

    POST    /tasks/log-level (io.dropwizard.servlets.tasks.LogConfigurationTask)
    POST    /tasks/gc (io.dropwizard.servlets.tasks.GarbageCollectionTask)

WARN  [2018-01-18 15:29:33,424] io.dropwizard.setup.AdminEnvironment: 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!    THIS APPLICATION HAS NO HEALTHCHECKS. THIS MEANS YOU WILL NEVER KNOW      !
!     IF IT DIES IN PRODUCTION, WHICH MEANS YOU WILL NEVER KNOW IF YOU'RE      !
!    LETTING YOUR USERS DOWN. YOU SHOULD ADD A HEALTHCHECK FOR EACH OF YOUR    !
!         APPLICATION'S DEPENDENCIES WHICH FULLY (BUT LIGHTLY) TESTS IT.       !
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
INFO  [2018-01-18 15:29:33,433] org.eclipse.jetty.server.handler.ContextHandler: Started i.d.j.MutableServletContextHandler@63f6bed1{/admin,null,AVAILABLE}
INFO  [2018-01-18 15:29:33,667] org.eclipse.jetty.server.AbstractConnector: Started DropwizardService@46185a1b{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
INFO  [2018-01-18 15:29:33,667] org.eclipse.jetty.server.Server: Started @3373ms
ERROR [2018-01-18 15:29:37,589] io.katharsis.core.internal.exception.KatharsisExceptionMapper: failed to process request
! io.katharsis.errorhandling.exception.ResourceException: Path is empty
! at io.katharsis.core.internal.dispatcher.path.PathBuilder.build(PathBuilder.java:57)
! at io.katharsis.rs.KatharsisFilter.dispatchRequest(KatharsisFilter.java:136)
! at io.katharsis.rs.KatharsisFilter.filter(KatharsisFilter.java:111)
! at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:132)
! at org.glassfish.jersey.server.ContainerFilteringStage.apply(ContainerFilteringStage.java:68)
! at org.glassfish.jersey.process.internal.Stages.process(Stages.java:197)
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:318)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
! at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
! at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1634)
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:34)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:50)
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:44)
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1621)
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:541)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1239)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:481)
! at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1141)
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:241)
! at io.dropwizard.jetty.ContextRoutingHandler.handle(ContextRoutingHandler.java:38)
! at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:561)
! at io.dropwizard.jetty.BiDiGzipHandler.handle(BiDiGzipHandler.java:68)
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:56)
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:169)
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
! at org.eclipse.jetty.server.Server.handle(Server.java:564)
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:320)
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:251)
! at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
! at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:110)
! at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:672)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:590)
! at java.lang.Thread.run(Thread.java:748)
0:0:0:0:0:0:0:1 - - [18/Jan/2018:15:29:37 +0000] "GET / HTTP/1.1" 500 79 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:57.0) Gecko/20100101 Firefox/57.0" 101

```

So it can't find the one resource and doesn't start

**Comment by corrspt** [comment]
I think this project is mostly abandoned, but you can find an active implementation of JSON:API for which there's a migration strategy from Katharsis, which is [crnk.io](http://www.crnk.io).

**Comment by charlesritchea** [comment]
Closing because project is abandoned
