### ISSUE TITLE
Nested Inclusion Throwing Error Upon Empty Initialized ArrayList And Nested Empty Initialized ArrayList

### ISSUE THREAD

**Issue by mitch2na** [katharsis-project/katharsis-framework#93]
When using the nested included function that references an empty initialized ArrayList that points to another empty initialized ArrayList i am getting the stack trace below:
```java
Caused by: io.katharsis.resource.exception.init.ResourceNotFoundInitializationException: Resource of class not found: java.util.ArrayList
	at io.katharsis.resource.registry.ResourceRegistry.getEntry(ResourceRegistry.java:62) ~[katharsis-core-2.5.0.jar:?]
	at io.katharsis.jackson.serializer.include.IncludedRelationshipExtractor.getRelationshipName(IncludedRelationshipExtractor.java:234) ~[katharsis-core-2.5.0.jar:?]
	at io.katharsis.jackson.serializer.include.IncludedRelationshipExtractor.populateIncludedResources(IncludedRelationshipExtractor.java:209) ~[katharsis-core-2.5.0.jar:?]
	at io.katharsis.jackson.serializer.include.IncludedRelationshipExtractor.populateIncludedRelationship(IncludedRelationshipExtractor.java:190) ~[katharsis-core-2.5.0.jar:?]
	at io.katharsis.jackson.serializer.include.IncludedRelationshipExtractor.populateIncludedRelationships(IncludedRelationshipExtractor.java:159) ~[katharsis-core-2.5.0.jar:?]
	at io.katharsis.jackson.serializer.include.IncludedRelationshipExtractor.extractIncludedResources(IncludedRelationshipExtractor.java:43) ~[katharsis-core-2.5.0.jar:?]
	at io.katharsis.jackson.serializer.BaseResponseSerializer.serializeSingle(BaseResponseSerializer.java:93) ~[katharsis-core-2.5.0.jar:?]
	at io.katharsis.jackson.serializer.BaseResponseSerializer.writeResponseWithResources(BaseResponseSerializer.java:76) ~[katharsis-core-2.5.0.jar:?]
	at io.katharsis.jackson.serializer.BaseResponseSerializer.serialize(BaseResponseSerializer.java:40) ~[katharsis-core-2.5.0.jar:?]
	at io.katharsis.jackson.serializer.BaseResponseSerializer.serialize(BaseResponseSerializer.java:17) ~[katharsis-core-2.5.0.jar:?]
	at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:130) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3559) ~[jackson-databind-2.6.3.jar:2.6.3]
	at com.fasterxml.jackson.databind.ObjectMapper.writeValue(ObjectMapper.java:2893) ~[jackson-databind-2.6.3.jar:2.6.3]
	at io.katharsis.invoker.KatharsisInvoker.dispatchRequest(KatharsisInvoker.java:119) ~[katharsis-servlet-2.5.0.jar:?]
	at io.katharsis.invoker.KatharsisInvoker.invoke(KatharsisInvoker.java:69) ~[katharsis-servlet-2.5.0.jar:?]
```

**Comment by meshuga** [comment]
Could you refine the issue?  There's too many references :wink:

**Comment by mitch2na** [comment]
Sorry just figured i would report this bug and then create a quick fix. Let me know if you want more detail, but the PR should hopefully explain the issue.
